---
title: "DB1140R2"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)

g <- read_excel("~/Documents/Experiments/9.23.25 DB1140.xlsx", 
    sheet = "Lum")
h <- read_excel("~/Documents/Experiments/9.23.25 DB1140.xlsx", 
    sheet = "OD")
i <- read_excel("~/Documents/Experiments/9.23.25 DB1140.xlsx", 
    sheet = "Lum OD")
m <- read_excel("~/Documents/Experiments/9.23.25 DB1140.xlsx", 
    sheet = "Avg Lum")
n <- read_excel("~/Documents/Experiments/9.23.25 DB1140.xlsx", 
    sheet = "Avg OD")
o <- read_excel("~/Documents/Experiments/9.23.25 DB1140.xlsx", 
    sheet = "Avg LO")

```

```{r GFP}

colors <- c("tac" = "seagreen","102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple", "110" = "cyan", "118" ="salmon")

p1 <- ggplot(g, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = C1, color="102"),linewidth=1) +
  geom_line(aes(y = E1, color="102"),linewidth=1) +
  geom_line(aes(y = G1, color="102"),linewidth=1) +
  geom_line(aes(y = A3, color="104"),linewidth=1) +
  geom_line(aes(y = C3, color="104"),linewidth=1) +
  geom_line(aes(y = E3, color="104"),linewidth=1) +
  geom_line(aes(y = G3, color="104"),linewidth=1) +
  geom_line(aes(y = A5, color="108"),linewidth=1) +
  geom_line(aes(y = C5, color="108"),linewidth=1) +
  geom_line(aes(y = E5, color="108"),linewidth=1) +
  geom_line(aes(y = G5, color="108"),linewidth=1) +
  geom_line(aes(y = A7, color="115"),linewidth=1) +
  geom_line(aes(y = C7, color="115"),linewidth=1) +
  geom_line(aes(y = E7, color="115"),linewidth=1) +
  geom_line(aes(y = G7, color="115"),linewidth=1) +
  geom_line(aes(y = A9, color="118"),linewidth=1) +
  geom_line(aes(y = C9, color="118"),linewidth=1) +
  geom_line(aes(y = E9, color="118"),linewidth=1) +
  geom_line(aes(y = G9, color="118"),linewidth=1) +
  geom_line(aes(y = A12, color="tac"),linewidth=1) +
  geom_line(aes(y = C12, color="tac"),linewidth=1) +
  geom_line(aes(y = E12, color="tac"),linewidth=1) +
  geom_line(aes(y = G12, color="tac"),linewidth=1) +
  annotate("rect", xmin = 0, xmax = 17, ymin = 0, ymax = 10720.33333, 
           alpha = .5)+
   labs(title=" All GFP",
        x ="Time (hours)", y = "GFP (AU)",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("All DBGFP.png")

p1 <- ggplot(h, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = C1, color="102"),linewidth=1) +
  geom_line(aes(y = E1, color="102"),linewidth=1) +
  geom_line(aes(y = G1, color="102"),linewidth=1) +
  geom_line(aes(y = A3, color="104"),linewidth=1) +
  geom_line(aes(y = C3, color="104"),linewidth=1) +
  geom_line(aes(y = E3, color="104"),linewidth=1) +
  geom_line(aes(y = G3, color="104"),linewidth=1) +
  geom_line(aes(y = A5, color="108"),linewidth=1) +
  geom_line(aes(y = C5, color="108"),linewidth=1) +
  geom_line(aes(y = E5, color="108"),linewidth=1) +
  geom_line(aes(y = G5, color="108"),linewidth=1) +
  geom_line(aes(y = A7, color="115"),linewidth=1) +
  geom_line(aes(y = C7, color="115"),linewidth=1) +
  geom_line(aes(y = E7, color="115"),linewidth=1) +
  geom_line(aes(y = G7, color="115"),linewidth=1) +
  geom_line(aes(y = A9, color="118"),linewidth=1) +
  geom_line(aes(y = C9, color="118"),linewidth=1) +
  geom_line(aes(y = E9, color="118"),linewidth=1) +
  geom_line(aes(y = G9, color="118"),linewidth=1) +
  geom_line(aes(y = A12, color="tac"),linewidth=1) +
  geom_line(aes(y = C12, color="tac"),linewidth=1) +
  geom_line(aes(y = E12, color="tac"),linewidth=1) +
  geom_line(aes(y = G12, color="tac"),linewidth=1) +
  annotate("rect", xmin = 0, xmax = 17, ymin = 0, ymax = 0.091537037, 
           alpha = .5)+
  scale_y_log10()+
   labs(title="All OD",
        x ="Time (hours)", y = "Log OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("All DBOD.png")
```

```{r OVL}
colors <- c("tac" = "seagreen","102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple", "110" = "cyan", "118" ="salmon")

r<- ggplot()+ 
  geom_point(data = data.frame(x = h$A1, y = g$A1), aes(x = x, y = y, color="102"))+
  geom_point(data = data.frame(x = h$C1, y = g$C1), aes(x = x, y = y, color="102"))+
  geom_point(data = data.frame(x = h$E1, y = g$E1), aes(x = x, y = y, color="102"))+
  geom_point(data = data.frame(x = h$G1, y = g$G1), aes(x = x, y = y, color="102"))+  
  geom_point(data = data.frame(x = h$A3, y = g$A3), aes(x = x, y = y, color="104"))+
  geom_point(data = data.frame(x = h$C3, y = g$C3), aes(x = x, y = y, color="104"))+
  geom_point(data = data.frame(x = h$E3, y = g$E3), aes(x = x, y = y, color="104"))+
  geom_point(data = data.frame(x = h$G3, y = g$G3), aes(x = x, y = y, color="104"))+
  geom_point(data = data.frame(x = h$A5, y = g$A5), aes(x = x, y = y, color="108"))+
  geom_point(data = data.frame(x = h$C5, y = g$C5), aes(x = x, y = y, color="108"))+
  geom_point(data = data.frame(x = h$E5, y = g$E5), aes(x = x, y = y, color="108"))+
  geom_point(data = data.frame(x = h$G5, y = g$G5), aes(x = x, y = y, color="108"))+
  geom_point(data = data.frame(x = h$A7, y = g$A7), aes(x = x, y = y, color="115"))+ 
  geom_point(data = data.frame(x = h$C7, y = g$C7), aes(x = x, y = y, color="115"))+
  geom_point(data = data.frame(x = h$E7, y = g$E7), aes(x = x, y = y, color="115"))+ 
  geom_point(data = data.frame(x = h$G7, y = g$G7), aes(x = x, y = y, color="115"))+
  geom_point(data = data.frame(x = h$A7, y = g$A7), aes(x = x, y = y, color="118"))+ 
  geom_point(data = data.frame(x = h$C7, y = g$C7), aes(x = x, y = y, color="118"))+
  geom_point(data = data.frame(x = h$E7, y = g$E7), aes(x = x, y = y, color="118"))+ 
  geom_point(data = data.frame(x = h$G7, y = g$G7), aes(x = x, y = y, color="118"))+
  geom_point(data = data.frame(x = h$A12, y = g$A12), aes(x = x, y = y, color="tac"))+ 
  geom_point(data = data.frame(x = h$C12, y = g$C12), aes(x = x, y = y, color="tac"))+ 
  geom_point(data = data.frame(x = h$E12, y = g$E12), aes(x = x, y = y, color="tac"))+
  geom_point(data = data.frame(x = h$G12, y = g$G12), aes(x = x, y = y, color="tac"))+
  labs(title="All OVL",
        x ="Optical Density", y = "GFP (AU)", color = "Legend") +
    scale_color_manual(values = colors)
r

#ggsave("All DbOVL.png")
```  
```{r GFP/OD}
colors <- c("tac" = "seagreen","102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple", "110" = "cyan", "118" ="salmon")
p1 <- ggplot(i, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = C1, color="102"),linewidth=1) +
  geom_line(aes(y = E1, color="102"),linewidth=1) +
  geom_line(aes(y = G1, color="102"),linewidth=1) +
  geom_line(aes(y = A3, color="104"),linewidth=1) +
  geom_line(aes(y = C3, color="104"),linewidth=1) +
  geom_line(aes(y = E3, color="104"),linewidth=1) +
  geom_line(aes(y = G3, color="104"),linewidth=1) +
  geom_line(aes(y = A5, color="108"),linewidth=1) +
  geom_line(aes(y = C5, color="108"),linewidth=1) +
  geom_line(aes(y = E5, color="108"),linewidth=1) +
  geom_line(aes(y = G5, color="108"),linewidth=1) +
  geom_line(aes(y = A7, color="115"),linewidth=1) +
  geom_line(aes(y = C7, color="115"),linewidth=1) +
  geom_line(aes(y = E7, color="115"),linewidth=1) +
  geom_line(aes(y = G7, color="115"),linewidth=1) +
  geom_line(aes(y = A9, color="118"),linewidth=1) +
  geom_line(aes(y = C9, color="118"),linewidth=1) +
  geom_line(aes(y = E9, color="118"),linewidth=1) +
  geom_line(aes(y = G9, color="118"),linewidth=1) +
  geom_line(aes(y = A12, color="tac"),linewidth=1) +
  geom_line(aes(y = C12, color="tac"),linewidth=1) +
  geom_line(aes(y = E12, color="tac"),linewidth=1) +
  geom_line(aes(y = G12, color="tac"),linewidth=1) +
  xlim(0,17)+
  ylim(0,400000)+
   labs(title="All DbGFP/OD",
        x ="Time (hours)", y = "GFP/OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("All DbGFPOD.png")
```

```{r Avg GFP}

colors <- c("tac" = "seagreen","102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple", "110" = "cyan", "118" ="salmon")

p1 <- ggplot(m, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = B1, color="104"),linewidth=1) +
  geom_line(aes(y = C1, color="108"),linewidth=1) +
  geom_line(aes(y = D1, color="115"),linewidth=1) +
  geom_line(aes(y = E1, color="118"),linewidth=1) +
  geom_line(aes(y = F1, color="tac"),linewidth=1) +

   labs(title="Avg All GFP",
        x ="Time (hours)", y = "GFP (AU)",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("Avg dbGFP.png")

p1 <- ggplot(n, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = B1, color="104"),linewidth=1) +
  geom_line(aes(y = C1, color="108"),linewidth=1) +
  geom_line(aes(y = D1, color="115"),linewidth=1) +
  geom_line(aes(y = E1, color="118"),linewidth=1) +
  geom_line(aes(y = F1, color="tac"),linewidth=1) +
  scale_y_log10()+
   labs(title="Avg All OD",
        x ="Time (hours)", y = "Log OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("Avg dbOD.png")
```

```{r Avg OVL}
colors <- c("tac" = "seagreen","102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple", "110" = "cyan", "118" ="salmon")

r<- ggplot()+ 
  geom_point(data = data.frame(x = n$A1, y = m$A1), aes(x = x, y = y, color="102"))+
   geom_point(data = data.frame(x = n$B1, y = m$B1), aes(x = x, y = y, color="104"))+
   geom_point(data = data.frame(x = n$C1, y = m$C1), aes(x = x, y = y, color="108"))+
   geom_point(data = data.frame(x = n$D1, y = m$D1), aes(x = x, y = y, color="115"))+
   geom_point(data = data.frame(x = n$E1, y = m$E1), aes(x = x, y = y, color="118"))+
   geom_point(data = data.frame(x = n$F1, y = m$F1), aes(x = x, y = y, color="tac"))+
  labs(title="Avg All OVL",
        x ="Optical Density", y = "GFP (AU)", color = "Legend") +
    scale_color_manual(values = colors)
r

#ggsave("Avg dbOVL.png")
```  

```{r Avg GFP/OD}
p1 <- ggplot(o, aes(x=Hours)) + 
 geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = B1, color="104"),linewidth=1) +
  geom_line(aes(y = C1, color="108"),linewidth=1) +
  geom_line(aes(y = D1, color="115"),linewidth=1) +
  geom_line(aes(y = E1, color="118"),linewidth=1) +
  geom_line(aes(y = F1, color="tac"),linewidth=1) +
   labs(title="Avg All GFP/OD",
        x ="Time (hours)", y = "GFP/OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("Avg dbGFPOD.png")
```

```{r}

ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red", se=FALSE) +
  labs(title = paste("R2 = ",signif(summary(fit)$r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}

ggplotRegression(lm( A1 ~ Hours, data = m))
ggplotRegression(lm( B1 ~ Hours, data = m))
ggplotRegression(lm( C1 ~ Hours, data = m))
ggplotRegression(lm( D1 ~ Hours, data = m))
ggplotRegression(lm( E1 ~ Hours, data = m))
ggplotRegression(lm( F1 ~ Hours, data = m))

ggplotRegression(lm( A1 ~ Hours, data = n))
ggplotRegression(lm( B1 ~ Hours, data = n))
ggplotRegression(lm( C1 ~ Hours, data = n))
ggplotRegression(lm( D1 ~ Hours, data = n))
ggplotRegression(lm( E1 ~ Hours, data = n))
ggplotRegression(lm( F1 ~ Hours, data = n))
```