---
title: "tacGFP"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(reshape2)
library(ggplot2)

g <- read_excel("~/Documents/Experiments/8.22.25 tacGFPEcoli.xlsx", 
    sheet = "Lum")
h <- read_excel("~/Documents/Experiments/8.22.25 tacGFPEcoli.xlsx", 
    sheet = "OD")
i <- read_excel("~/Documents/Experiments/8.22.25 tacGFPEcoli.xlsx", 
    sheet = "Lum OD")
l <- read_excel("~/Documents/Experiments/9.4.25 Promoters.xlsx", 
    sheet = "Lum")
m <- read_excel("~/Documents/Experiments/9.4.25 Promoters.xlsx", 
    sheet = "OD")
n <- read_excel("~/Documents/Experiments/9.4.25 Promoters.xlsx", 
    sheet = "Lum OD")
o <- read_excel("~/Documents/Experiments/9.9.25 Promoters.xlsx", 
    sheet = "Lum")
p <- read_excel("~/Documents/Experiments/9.9.25 Promoters.xlsx", 
    sheet = "OD")
q <- read_excel("~/Documents/Experiments/9.9.25 Promoters.xlsx", 
    sheet = "Lum OD")

```

```{r tac}
colors <- c("GFP" = "seagreen", "Blank" = "gray")

p1 <- ggplot(g, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="GFP"),linewidth=1) +
  geom_line(aes(y = C1, color="GFP"),linewidth=1) +
  geom_line(aes(y = E1, color="GFP"),linewidth=1)+
  geom_line(aes(y = G1, color="GFP"),linewidth=1)+
  geom_line(aes(y = A3, color="GFP"),linewidth=1) +
  geom_line(aes(y = C3, color="GFP"),linewidth=1) +
  geom_line(aes(y = E3, color="GFP"),linewidth=1)+
  geom_point(aes(y = A1, color="GFP")) +
  geom_point(aes(y = C1, color="GFP")) +
  geom_point(aes(y = E1, color="GFP"))+
  geom_point(aes(y = G1, color="GFP"))+
  geom_point(aes(y = A3, color="GFP")) +
  geom_point(aes(y = C3, color="GFP")) +
  geom_point(aes(y = E3, color="GFP"))+
   labs(title=" tac Lum",
        x ="Time (hours)", y = "Luminescence (AU)",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("tac Lum.png")

p1 <- ggplot(h, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="GFP"),linewidth=1) +
  geom_line(aes(y = C1, color="GFP"),linewidth=1) +
  geom_line(aes(y = E1, color="GFP"),linewidth=1)+
  geom_line(aes(y = G1, color="GFP"),linewidth=1)+
  geom_line(aes(y = A3, color="GFP"),linewidth=1) +
  geom_line(aes(y = C3, color="GFP"),linewidth=1) +
  geom_line(aes(y = E3, color="GFP"),linewidth=1)+
  geom_point(aes(y = A1, color="GFP")) +
  geom_point(aes(y = C1, color="GFP")) +
  geom_point(aes(y = E1, color="GFP"))+
  geom_point(aes(y = G1, color="GFP"))+
  geom_point(aes(y = A3, color="GFP")) +
  geom_point(aes(y = C3, color="GFP")) +
  geom_point(aes(y = E3, color="GFP"))+
  scale_y_log10()+
   labs(title="tac OD",
        x ="Time (hours)", y = "Log OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("tac OD.png")
```

```{r tac OVL}
colors <- c("GFP" = "seagreen", "Blank" = "gray")
r<- ggplot()+ 
  geom_point(data = data.frame(x = h$A1, y = g$A1), aes(x = x, y = y, color="GFP"))+
 geom_point(data = data.frame(x = h$C1, y = g$C1), aes(x = x, y = y, color="GFP"))+
  geom_point(data = data.frame(x = h$E1, y = g$E1), aes(x = x, y = y, color="GFP"))+
  geom_point(data = data.frame(x = h$G1, y = g$G1), aes(x = x, y = y, color="GFP"))+
   geom_point(data = data.frame(x = h$A3, y = g$A3), aes(x = x, y = y, color="GFP"))+
 geom_point(data = data.frame(x = h$C3, y = g$C3), aes(x = x, y = y, color="GFP"))+
  geom_point(data = data.frame(x = h$E3, y = g$E3), aes(x = x, y = y, color="GFP"))+
labs(title="tac OVL",
        x ="Optical Density", y = "Luminescence (AU)", color = "Legend") +
    scale_color_manual(values = colors)
r

#ggsave("tac OVL.png")

```

```{r tac Lum/OD}
colors <- c("GFP" = "seagreen", "Blank" = "gray")
p1 <- ggplot(i, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="GFP"),linewidth=1) +
  geom_line(aes(y = C1, color="GFP"),linewidth=1) +
  geom_line(aes(y = E1, color="GFP"),linewidth=1)+
  geom_line(aes(y = G1, color="GFP"),linewidth=1)+
  geom_line(aes(y = A3, color="GFP"),linewidth=1) +
  geom_line(aes(y = C3, color="GFP"),linewidth=1) +
  geom_line(aes(y = E3, color="GFP"),linewidth=1)+
  geom_point(aes(y = A1, color="GFP")) +
  geom_point(aes(y = C1, color="GFP")) +
  geom_point(aes(y = E1, color="GFP"))+
  geom_point(aes(y = G1, color="GFP"))+
  geom_point(aes(y = A3, color="GFP")) +
  geom_point(aes(y = C3, color="GFP")) +
  geom_point(aes(y = E3, color="GFP"))+
   labs(title="tac Lum/OD",
        x ="Time (hours)", y = "Lum/OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("tac LumOD.png")
```

```{r 102 Lum}
colors <- c("102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple")

p1 <- ggplot(l, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = C1, color="102"),linewidth=1) +
  #geom_line(aes(y = E1, color="102"),linewidth=1)+
  #geom_line(aes(y = G1, color="102"),linewidth=1)+
  geom_line(aes(y = A3, color="104"),linewidth=1) +
  geom_line(aes(y = C3, color="104"),linewidth=1) +
  geom_line(aes(y = E3, color="104"),linewidth=1)+
  geom_line(aes(y = E3, color="104"),linewidth=1)+
  geom_line(aes(y = A5, color="108"),linewidth=1) +
  geom_line(aes(y = C5, color="108"),linewidth=1) +
  geom_line(aes(y = E5, color="108"),linewidth=1)+
  geom_line(aes(y = E5, color="108"),linewidth=1)+
  geom_line(aes(y = A7, color="115"),linewidth=1) +
  geom_line(aes(y = C7, color="115"),linewidth=1) +
  geom_line(aes(y = E7, color="115"),linewidth=1)+
  geom_line(aes(y = E7, color="115"),linewidth=1)+
   labs(title="Promoters 102-115 Lum",
        x ="Time (hours)", y = "Luminescence (AU)",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("102 Lum.png")


p1 <- ggplot(m, aes(x=Hours)) + 
 geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = C1, color="102"),linewidth=1) +
  #geom_line(aes(y = E1, color="102"),linewidth=1)+
  #geom_line(aes(y = G1, color="102"),linewidth=1)+
  geom_line(aes(y = A3, color="104"),linewidth=1) +
  geom_line(aes(y = C3, color="104"),linewidth=1) +
  geom_line(aes(y = E3, color="104"),linewidth=1)+
  geom_line(aes(y = E3, color="104"),linewidth=1)+
  geom_line(aes(y = A5, color="108"),linewidth=1) +
  geom_line(aes(y = C5, color="108"),linewidth=1) +
  geom_line(aes(y = E5, color="108"),linewidth=1)+
  geom_line(aes(y = E5, color="108"),linewidth=1)+
  geom_line(aes(y = A7, color="115"),linewidth=1) +
  geom_line(aes(y = C7, color="115"),linewidth=1) +
  geom_line(aes(y = E7, color="115"),linewidth=1)+
  geom_line(aes(y = E7, color="115"),linewidth=1)+
  scale_y_log10()+
   labs(title="Promoters 102-115 OD",
        x ="Time (hours)", y = "Log OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("102 OD.png")
```

```{r 102 OVL}

colors <- c("102" = "pink", "104" = "orange", "108" = "lightblue", "115" = "purple")

r<- ggplot()+ 
  geom_point(data = data.frame(x = m$A1, y = l$A1), aes(x = x, y = y, color="102"))+
 geom_point(data = data.frame(x = m$C1, y = l$C1), aes(x = x, y = y, color="102"))+
  #geom_point(data = data.frame(x = m$E1, y = l$E1), aes(x = x, y = y, color="102"))+
  #geom_point(data = data.frame(x = m$G1, y = l$G1), aes(x = x, y = y, color="102"))+
   geom_point(data = data.frame(x = m$A3, y = l$A3), aes(x = x, y = y, color="104"))+
 geom_point(data = data.frame(x = m$C3, y = l$C3), aes(x = x, y = y, color="104"))+
  geom_point(data = data.frame(x = m$E3, y = l$E3), aes(x = x, y = y, color="104"))+
   geom_point(data = data.frame(x = m$G3, y = l$G3), aes(x = x, y = y, color="104"))+ 
  geom_point(data = data.frame(x = m$A5, y = l$A5), aes(x = x, y = y, color="108"))+
 geom_point(data = data.frame(x = m$C5, y = l$C5), aes(x = x, y = y, color="108"))+
  geom_point(data = data.frame(x = m$E5, y = l$E5), aes(x = x, y = y, color="108"))+
   geom_point(data = data.frame(x = m$G5, y = l$G5), aes(x = x, y = y, color="108"))+
   geom_point(data = data.frame(x = m$A7, y = l$A7), aes(x = x, y = y, color="115"))+
 geom_point(data = data.frame(x = m$C7, y = l$C7), aes(x = x, y = y, color="115"))+
  geom_point(data = data.frame(x = m$E7, y = l$E7), aes(x = x, y = y, color="115"))+
   geom_point(data = data.frame(x = m$G7, y = l$G7), aes(x = x, y = y, color="115"))+
labs(title="Promoters 102-115 OVL",
        x ="Optical Density", y = "Luminescence (AU)", color = "Legend") +
    scale_color_manual(values = colors)
r

#ggsave("102 OVL.png")

```

```{r 102 Lum/OD}
p1 <- ggplot(n, aes(x=Hours)) + 
 geom_line(aes(y = A1, color="102"),linewidth=1) +
  geom_line(aes(y = C1, color="102"),linewidth=1) +
  #geom_line(aes(y = E1, color="102"),linewidth=1)+
  #geom_line(aes(y = G1, color="102"),linewidth=1)+
  geom_line(aes(y = A3, color="104"),linewidth=1) +
  geom_line(aes(y = C3, color="104"),linewidth=1) +
  geom_line(aes(y = E3, color="104"),linewidth=1)+
  geom_line(aes(y = E3, color="104"),linewidth=1)+
  geom_line(aes(y = A5, color="108"),linewidth=1) +
  geom_line(aes(y = C5, color="108"),linewidth=1) +
  geom_line(aes(y = E5, color="108"),linewidth=1)+
  geom_line(aes(y = E5, color="108"),linewidth=1)+
  geom_line(aes(y = A7, color="115"),linewidth=1) +
  geom_line(aes(y = C7, color="115"),linewidth=1) +
  geom_line(aes(y = E7, color="115"),linewidth=1)+
  geom_line(aes(y = E7, color="115"),linewidth=1)+
   labs(title="Promoters 102-115 Lum/OD",
        x ="Time (hours)", y = "Lum/OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("102 LumOD.png")
```

```{r 110 Lum}
colors <- c("110" = "cyan", "118" ="salmon")

p1 <- ggplot(o, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="110"),linewidth=1) +
  geom_line(aes(y = C1, color="110"),linewidth=1) +
  geom_line(aes(y = E1, color="110"),linewidth=1)+
  geom_line(aes(y = G1, color="110"),linewidth=1)+
  geom_line(aes(y = A3, color="110"),linewidth=1) +
  geom_line(aes(y = C3, color="110"),linewidth=1) +
  geom_line(aes(y = E3, color="110"),linewidth=1)+
  geom_line(aes(y = E3, color="110"),linewidth=1)+
  geom_line(aes(y = A5, color="118"),linewidth=1) +
  geom_line(aes(y = C5, color="118"),linewidth=1) +
  geom_line(aes(y = E5, color="118"),linewidth=1)+
  geom_line(aes(y = E5, color="118"),linewidth=1)+
  geom_line(aes(y = A7, color="118"),linewidth=1) +
  geom_line(aes(y = C7, color="118"),linewidth=1) +
  geom_line(aes(y = E7, color="118"),linewidth=1)+
  geom_line(aes(y = E7, color="118"),linewidth=1)+
   labs(title="Promoters 110-118 Lum",
        x ="Time (hours)", y = "Luminescence (AU)",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("110 Lum.png")


p1 <- ggplot(p, aes(x=Hours)) + 
 geom_line(aes(y = A1, color="110"),linewidth=1) +
  geom_line(aes(y = C1, color="110"),linewidth=1) +
  geom_line(aes(y = E1, color="110"),linewidth=1)+
  geom_line(aes(y = G1, color="110"),linewidth=1)+
  geom_line(aes(y = A3, color="110"),linewidth=1) +
  geom_line(aes(y = C3, color="110"),linewidth=1) +
  geom_line(aes(y = E3, color="110"),linewidth=1)+
  geom_line(aes(y = E3, color="110"),linewidth=1)+
  geom_line(aes(y = A5, color="118"),linewidth=1) +
  geom_line(aes(y = C5, color="118"),linewidth=1) +
  geom_line(aes(y = E5, color="118"),linewidth=1)+
  geom_line(aes(y = E5, color="118"),linewidth=1)+
  geom_line(aes(y = A7, color="118"),linewidth=1) +
  geom_line(aes(y = C7, color="118"),linewidth=1) +
  geom_line(aes(y = E7, color="118"),linewidth=1)+
  geom_line(aes(y = E7, color="118"),linewidth=1)+
  scale_y_log10()+
   labs(title="Promoters 110-118 OD",
        x ="Time (hours)", y = "Log OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("110 OD.png")
```

```{r 110 OVL}

colors <- c("110" = "cyan", "118" ="salmon")

r<- ggplot()+ 
  geom_point(data = data.frame(x = p$A1, y = o$A1), aes(x = x, y = y, color="110"))+
 geom_point(data = data.frame(x = p$C1, y = o$C1), aes(x = x, y = y, color="110"))+
  geom_point(data = data.frame(x = p$E1, y = o$E1), aes(x = x, y = y, color="110"))+
  geom_point(data = data.frame(x = p$G1, y = o$G1), aes(x = x, y = y, color="110"))+
   geom_point(data = data.frame(x = p$A3, y = o$A3), aes(x = x, y = y, color="110"))+
 geom_point(data = data.frame(x = p$C3, y = o$C3), aes(x = x, y = y, color="110"))+
  geom_point(data = data.frame(x = p$E3, y = o$E3), aes(x = x, y = y, color="110"))+
   geom_point(data = data.frame(x = p$G3, y = o$G3), aes(x = x, y = y, color="110"))+ 
  geom_point(data = data.frame(x = p$A5, y = o$A5), aes(x = x, y = y, color="118"))+
 geom_point(data = data.frame(x = p$C5, y = o$C5), aes(x = x, y = y, color="118"))+
  geom_point(data = data.frame(x = p$E5, y = o$E5), aes(x = x, y = y, color="118"))+
   geom_point(data = data.frame(x = p$G5, y = o$G5), aes(x = x, y = y, color="118"))+
   geom_point(data = data.frame(x = p$A7, y = o$A7), aes(x = x, y = y, color="118"))+
 geom_point(data = data.frame(x = p$C7, y = o$C7), aes(x = x, y = y, color="118"))+
  geom_point(data = data.frame(x = p$E7, y = o$E7), aes(x = x, y = y, color="118"))+
   geom_point(data = data.frame(x = p$G7, y = o$G7), aes(x = x, y = y, color="118"))+
labs(title="Promoters 110-118 OVL",
        x ="Optical Density", y = "Luminescence (AU)", color = "Legend") +
    scale_color_manual(values = colors)
r

#ggsave("110 OVL.png")

```

```{r 110 Lum/OD}

colors <- c("110" = "cyan", "118" ="salmon")

p1 <- ggplot(q, aes(x=Hours)) + 
 geom_line(aes(y = A1, color="110"),linewidth=1) +
  geom_line(aes(y = C1, color="110"),linewidth=1) +
  geom_line(aes(y = E1, color="110"),linewidth=1)+
  geom_line(aes(y = G1, color="110"),linewidth=1)+
  geom_line(aes(y = A3, color="110"),linewidth=1) +
  geom_line(aes(y = C3, color="110"),linewidth=1) +
  geom_line(aes(y = E3, color="110"),linewidth=1)+
  geom_line(aes(y = E3, color="110"),linewidth=1)+
  geom_line(aes(y = A5, color="118"),linewidth=1) +
  geom_line(aes(y = C5, color="118"),linewidth=1) +
  geom_line(aes(y = E5, color="118"),linewidth=1)+
  geom_line(aes(y = E5, color="118"),linewidth=1)+
  geom_line(aes(y = A7, color="118"),linewidth=1) +
  geom_line(aes(y = C7, color="118"),linewidth=1) +
  geom_line(aes(y = E7, color="118"),linewidth=1)+
  geom_line(aes(y = E7, color="118"),linewidth=1)+
   labs(title="Promoters 110-118 Lum/OD",
        x ="Time (hours)", y = "Lum/OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("110 LumOD.png")
```